package ultimate.javaee.helloworld.model;

/**
 * This is a simple Person POJO (plain old java object).
 * 
 * In order to be able to compare Persons with each other it is important to implement
 * {@link Object#hashCode()} and {@link Object#equals(Object)} for this class. Otherwise containers
 * (e.g. lists) won't be able to check for existing Persons with matching first name and last name.
 * 
 * Additionally we implemented {@link Object#toString()} here to return the object as JSON, so we
 * can go without any JSON library for returning results for this simple example.
 * 
 * @author ultimate
 */
public class Person
{
	/**
	 * The first name of the Person
	 */
	private String	firstname;
	/**
	 * The last name of the Person
	 */
	private String	lastname;

	/**
	 * Create a new Person with no first name and no last name
	 */
	public Person()
	{

	}

	/**
	 * Create a new Person with the given first name and last name
	 * 
	 * @param firstname - the first name for the Person
	 * @param lastname - the last name for the Person
	 */
	public Person(String firstname, String lastname)
	{
		super();
		this.firstname = firstname;
		this.lastname = lastname;
	}

	/**
	 * The first name of the Person
	 * 
	 * @return firstname
	 */
	public String getFirstname()
	{
		return firstname;
	}

	/**
	 * The first name of the Person
	 * 
	 * @param firstname - the new first name for the Person
	 */
	public void setFirstname(String firstname)
	{
		this.firstname = firstname;
	}

	/**
	 * The last name of the Person
	 * 
	 * @return lastname
	 */
	public String getLastname()
	{
		return lastname;
	}

	/**
	 * The last name of the Person
	 * 
	 * @param lastname - the new last name for the Person
	 */
	public void setLastname(String lastname)
	{
		this.lastname = lastname;
	}

	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode()
	{
		// auto generated by eclipse
		final int prime = 31;
		int result = 1;
		result = prime * result + ((firstname == null) ? 0 : firstname.hashCode());
		result = prime * result + ((lastname == null) ? 0 : lastname.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj)
	{
		// auto generated by eclipse
		if(this == obj)
			return true;
		if(obj == null)
			return false;
		if(getClass() != obj.getClass())
			return false;
		Person other = (Person) obj;
		if(firstname == null)
		{
			if(other.firstname != null)
				return false;
		}
		else if(!firstname.equals(other.firstname))
			return false;
		if(lastname == null)
		{
			if(other.lastname != null)
				return false;
		}
		else if(!lastname.equals(other.lastname))
			return false;
		return true;
	}

	/**
	 * Return the Person as JSON
	 */
	@Override
	public String toString()
	{
		// hardcoded JSON creation
		return "{\"firstname\":\"" + firstname + "\", \"lastname\":\"" + lastname + "\"}";
	}

}
